### ISSUE TITLE
[BUG] ScriptChunk

### ISSUE THREAD

**Issue by rachyrachyrach** [bitcoin-sv/py-sdk#11]
## Bug Description

ScriptChunk wasn't found when trying to work with code in this file: /bsv/script/__init__.py
https://github.com/bitcoin-sv/py-sdk/blob/master/bsv/script/__init__.py

I had to add this for my import. 
`from bsv.script.script import ScriptChunk`

## Expected Behavior

I was expecting to add `from bsv import ScriptChunk`

## Actual Behavior

```
python3 test_scriptchunk.py 
Traceback (most recent call last):
  File "/Users/rachael/github/bsv-transaction-bsv-sdk/test_scriptchunk.py", line 1, in <module>
    from bsv.script import Script, ScriptChunk
ImportError: cannot import name 'ScriptChunk' from 'bsv.script' (/Users/rachael/github/4chain-bsv-sdk/.venv/lib/python3.9/site-packages/bsv/script/__init__.py)
```

## Environment

- OS: MacOS
- venv
- pip 21.2.4 from /Users/rachael/github/4chain-bsv-sdk/.venv/lib/python3.9/site-packages/pip (python 3.9)
- Python 3.9.6

Name: bsv-sdk
Version: 0.5.2
Summary: BSV BLOCKCHAIN | Software Development Kit for Python
Home-page: https://github.com/bitcoin-sv/py-sdk
Author: Aaron
Author-email: aaron@scrypt.io
License: 
Location: /Users/rachael/github/4chain-bsv-sdk/.venv/lib/python3.9/site-packages
Requires: requests, coincurve, pycryptodomex
Required-by: 
[requirements.txt](https://github.com/user-attachments/files/18084833/requirements.txt)

**Comment by sirdeggen** [comment]
thanks for raising the issue - Ken Sato will be on it soon

**Comment by ALiberalVoluntarist** [comment]
@rachyrachyrach We fix the issue of Scriptchunk. thanks
